from selenium.webdriver.common.by import By


class Locators:
    ENTER_ACCOUNT_BUTTON = (By.XPATH, "//button[contains(text(),'Войти в аккаунт')]")
    PERSONAL_ACCOUNT_BUTTON = (By.XPATH, "//p[contains(text(),'Личный Кабинет')]")
    ENTER_BUTTON = (By.XPATH, "//button[contains(text(),'Войти')]")
    EXIT_BUTTON = (By.XPATH, "//button[contains(text(),'Выход')]")
    REGISTRATION_BUTTON = (By.XPATH, "//a[contains(text(),'Зарегистрироваться')]")
    ENTER_FROM_REGISTRATION_BUTTON = (By.XPATH, "//a[contains(text(),'Войти')]")
    PASSWORD_RECOVERY_BUTTON = (By.XPATH, "//a[contains(text(),'Восстановить пароль')]")
    INPUT_MAIL_BUTTON = (By.XPATH, "//input[@type='text']")
    INPUT_PASSWORD_BUTTON = (By.XPATH, "//input[@type='password']")
    PLACE_ORDER_BUTTON = (By.XPATH, "//button[contains(text(),'Оформить заказ')]")
    DETAILS_OF_INGRIDENTS_BUTTON = (By.XPATH, "//h2[contains(text(), 'Детали')]")
    BEEF_METEORITE_BUTTON = (By.XPATH, "//p[contains(text(),'Говяжий метеорит (отбивная)')]")
    FILLING_BUTTON = (By.XPATH, "//span[contains(text(),'Начинки')]")
    SAUCE_BUTTON = (By.XPATH, "//span[contains(text(),'Соусы')]")
    SAUCE_ANTARIAN_BUTTON = (By.XPATH, "//p[contains(text(),'Соус с шипами Антарианского плоскоходца')]")
    FILLING_CHEEZE_WITH_ASTEROID_MOLD = (By.XPATH, "//p[contains(text(),'Сыр с астероидной плесенью')]")
    PERSONAL_ACCOUNT_NAME_INFO_BUTTON = (By.XPATH, "//input[@name='Name']")
    PERSONAL_ACCOUNT_MAIL_INFO_BUTTON = (By.XPATH, "//input[contains(@value,'@')]")
    CONSTRUCTOR_BUTTON = (By.XPATH, "//p[contains(text(),'Конструктор')]")
    ASSEMBLE_BURGER_TEXT = (By.XPATH, "//h1[contains(text(),'Соберите бургер')]")
    STELLAR_BURGER_BUTTON = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/header[1]/nav[1]/div[1]/a[1]/*[name()='svg'][1]")
    REGISTRATION_INPUT_NAME_BUTTON = (By.XPATH, "(//input[@name='name'])[1]")
    REGISTRATION_INPUT_EMAIL_BUTTON = (By.XPATH, "(//input[@name='name'])[2]")
    REGISTRATION_INPUT_PASSWORD_BUTTON = (By.CSS_SELECTOR, "input[name='Пароль']")
    REGISTRATION_CHECK_BUTTON = (By.XPATH, "//button[contains(text(),'Зарегистрироваться')]")
